### ISSUE TITLE
Crashloop when too much data

### ISSUE THREAD

**Issue by Oneloutre** [Trigus42/alpine-qbittorrentvpn#65] opened 2024-05-05 14:39 UTC
I got an issue since a few weeks,

When I add more than 20Gb, it fails after 2-5 min then restarts then crash etc... I have to de-activate a few files and then enable it when the others are done. Do you maybe know how to fix it ?

Thanks in advance,

**Comment by Trigus42** [comment] 2024-05-09 13:15
Can you please post the container and the QBt logs of such a crash?

**Comment by Oneloutre** [comment] 2024-05-12 20:30
Yes, I'm gonna do it immediately. I will provide my docker compose too and everything

**Comment by Oneloutre** [comment] 2024-05-12 21:39
Here are my different files/logs :

docker logs mycontainer : 
```txt

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-environment.sh: executing... 
2024-05-12 20:44:05 [INFO] HEALTH_CHECK_HOST is not set. Using default host 1.1.1.1
2024-05-12 20:44:05 [INFO] HEALTH_CHECK_INTERVAL is not set. Using default interval of 5s
2024-05-12 20:44:05 [INFO] HEALTH_CHECK_TIMEOUT is not set. Using default interval of 5s
2024-05-12 20:44:05 [INFO] PUID not defined. Defaulting to 1000
2024-05-12 20:44:05 [INFO] PGID not defined. Defaulting to 1000
2024-05-12 20:44:05 [INFO] An user with PUID 1000 already exists in /etc/passwd, nothing to do.
2024-05-12 20:44:05 [INFO] VPN_ENABLED not defined (via -e VPN_ENABLED), defaulting to 'yes'
2024-05-12 20:44:05 [INFO] VPN_TYPE defined as 'wireguard'
2024-05-12 20:44:05 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2024-05-12 20:44:05 [INFO] Adding 1.1.1.1 to resolv.conf
2024-05-12 20:44:05 [INFO] Adding 8.8.8.8 to resolv.conf
2024-05-12 20:44:05 [INFO] Adding 1.0.0.1 to resolv.conf
2024-05-12 20:44:05 [INFO] Adding 8.8.4.4 to resolv.conf
[cont-init.d] 10-environment.sh: exited 0.
[cont-init.d] 20-vpn.sh: executing... 
2024-05-12 20:44:05 [INFO] Choosen VPN config: 'onelots.conf'
dos2unix: converting file /config/wireguard/onelots.conf to Unix format...
2024-05-12 20:44:05 [INFO] VPN remote line defined as '[IP of my VPN]:51820'
2024-05-12 20:44:05 [INFO] VPN_REMOTE defined as '[IP of my VPN]'
2024-05-12 20:44:05 [INFO] VPN_PORT defined as '51820'
2024-05-12 20:44:05 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2024-05-12 20:44:05 [INFO] VPN_DEVICE_TYPE set as 'onelots'
2024-05-12 20:44:05 [INFO] Starting WireGuard...
--------------------
Warning: `/config/wireguard/onelots.conf' is world accessible
[#] ip link add onelots type wireguard
[#] wg setconf onelots /dev/fd/63
[#] ip -4 address add 10.7.0.2/24 dev onelots
[#] ip link set mtu 1420 up dev onelots
[#] resolvconf -a onelots -m 0 -x
[#] wg set onelots fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev onelots table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
--------------------
[cont-init.d] 20-vpn.sh: exited 0.
[cont-init.d] 30-network.sh: executing... 
[cont-init.d] 30-network.sh: exited 0.
[cont-init.d] 40-qbittorrent-setup.sh: executing... 
2024-05-12 20:44:05 [WARNING] ENABLE_SSL is set to , SSL is not enabled. This could cause issues with logging if other apps use the same Cookie name (SID).
2024-05-12 20:44:05 [WARNING] If you manage the SSL config yourself, you can ignore this.
2024-05-12 20:44:05 [WARNING] UMASK not defined (via -e UMASK), defaulting to '002'
[cont-init.d] 40-qbittorrent-setup.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
2024-05-12 20:44:05 [INFO] Logging to /config/qBittorrent/data/logs/qbittorrent.log.
[services.d] done.
2024-05-12 20:44:05 [INFO] Trying to ping 1.1.1.1 and 8.8.8.8 over the docker interface for 1 second...
2024-05-12 20:44:07 [INFO] Success: Could not connect. This means the firewall is most likely working properly.
2024-05-12 20:44:07 [INFO] qBittorrent started with PID 494
2024-05-12 20:46:45 [NOTICE] Network seems to be down. Retrying..
2024-05-12 20:46:45 [ERROR] Network is down. Exiting..
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-environment.sh: executing... 
2024-05-12 20:46:49 [INFO] HEALTH_CHECK_HOST is not set. Using default host 1.1.1.1
2024-05-12 20:46:49 [INFO] HEALTH_CHECK_INTERVAL is not set. Using default interval of 5s
2024-05-12 20:46:49 [INFO] HEALTH_CHECK_TIMEOUT is not set. Using default interval of 5s
2024-05-12 20:46:49 [INFO] PUID not defined. Defaulting to 1000
2024-05-12 20:46:49 [INFO] PGID not defined. Defaulting to 1000
2024-05-12 20:46:49 [INFO] An user with PUID 1000 already exists in /etc/passwd, nothing to do.
2024-05-12 20:46:49 [INFO] VPN_ENABLED not defined (via -e VPN_ENABLED), defaulting to 'yes'
2024-05-12 20:46:49 [INFO] VPN_TYPE defined as 'wireguard'
2024-05-12 20:46:49 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2024-05-12 20:46:49 [INFO] Adding 1.1.1.1 to resolv.conf
2024-05-12 20:46:49 [INFO] Adding 8.8.8.8 to resolv.conf
2024-05-12 20:46:49 [INFO] Adding 1.0.0.1 to resolv.conf
2024-05-12 20:46:49 [INFO] Adding 8.8.4.4 to resolv.conf
[cont-init.d] 10-environment.sh: exited 0.
[cont-init.d] 20-vpn.sh: executing... 
2024-05-12 20:46:49 [INFO] Choosen VPN config: 'onelots.conf'
dos2unix: converting file /config/wireguard/onelots.conf to Unix format...
2024-05-12 20:46:49 [INFO] VPN remote line defined as '[IP of my VPN]:51820'
2024-05-12 20:46:49 [INFO] VPN_REMOTE defined as '[IP of my VPN]'
2024-05-12 20:46:49 [INFO] VPN_PORT defined as '51820'
2024-05-12 20:46:49 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2024-05-12 20:46:49 [INFO] VPN_DEVICE_TYPE set as 'onelots'
2024-05-12 20:46:49 [INFO] Starting WireGuard...
--------------------
Warning: `/config/wireguard/onelots.conf' is world accessible
[#] ip link add onelots type wireguard
[#] wg setconf onelots /dev/fd/63
[#] ip -4 address add 10.7.0.2/24 dev onelots
[#] ip link set mtu 1420 up dev onelots
[#] resolvconf -a onelots -m 0 -x
[#] wg set onelots fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev onelots table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
--------------------
[cont-init.d] 20-vpn.sh: exited 0.
[cont-init.d] 30-network.sh: executing... 
[cont-init.d] 30-network.sh: exited 0.
[cont-init.d] 40-qbittorrent-setup.sh: executing... 
2024-05-12 20:46:49 [WARNING] ENABLE_SSL is set to , SSL is not enabled. This could cause issues with logging if other apps use the same Cookie name (SID).
2024-05-12 20:46:49 [WARNING] If you manage the SSL config yourself, you can ignore this.
2024-05-12 20:46:49 [WARNING] UMASK not defined (via -e UMASK), defaulting to '002'
[cont-init.d] 40-qbittorrent-setup.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
2024-05-12 20:46:49 [INFO] Logging to /config/qBittorrent/data/logs/qbittorrent.log.
[services.d] done.
2024-05-12 20:46:49 [INFO] Trying to ping 1.1.1.1 and 8.8.8.8 over the docker interface for 1 second...
2024-05-12 20:46:51 [INFO] Success: Could not connect. This means the firewall is most likely working properly.
2024-05-12 20:46:51 [INFO] qBittorrent started with PID 494
2024-05-12 20:58:56 [NOTICE] Network seems to be down. Retrying..
2024-05-12 20:58:56 [ERROR] Network is down. Exiting..
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-environment.sh: executing... 
2024-05-12 20:59:00 [INFO] HEALTH_CHECK_HOST is not set. Using default host 1.1.1.1
2024-05-12 20:59:00 [INFO] HEALTH_CHECK_INTERVAL is not set. Using default interval of 5s
2024-05-12 20:59:00 [INFO] HEALTH_CHECK_TIMEOUT is not set. Using default interval of 5s
2024-05-12 20:59:00 [INFO] PUID not defined. Defaulting to 1000
2024-05-12 20:59:00 [INFO] PGID not defined. Defaulting to 1000
2024-05-12 20:59:00 [INFO] An user with PUID 1000 already exists in /etc/passwd, nothing to do.
2024-05-12 20:59:00 [INFO] VPN_ENABLED not defined (via -e VPN_ENABLED), defaulting to 'yes'
2024-05-12 20:59:00 [INFO] VPN_TYPE defined as 'wireguard'
2024-05-12 20:59:00 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
2024-05-12 20:59:00 [INFO] Adding 1.1.1.1 to resolv.conf
2024-05-12 20:59:00 [INFO] Adding 8.8.8.8 to resolv.conf
2024-05-12 20:59:00 [INFO] Adding 1.0.0.1 to resolv.conf
2024-05-12 20:59:00 [INFO] Adding 8.8.4.4 to resolv.conf
[cont-init.d] 10-environment.sh: exited 0.
[cont-init.d] 20-vpn.sh: executing... 
2024-05-12 20:59:00 [INFO] Choosen VPN config: 'onelots.conf'
dos2unix: converting file /config/wireguard/onelots.conf to Unix format...
2024-05-12 20:59:00 [INFO] VPN remote line defined as '[IP of my VPN]:51820'
2024-05-12 20:59:00 [INFO] VPN_REMOTE defined as '[IP of my VPN]'
2024-05-12 20:59:00 [INFO] VPN_PORT defined as '51820'
2024-05-12 20:59:00 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
2024-05-12 20:59:00 [INFO] VPN_DEVICE_TYPE set as 'onelots'
2024-05-12 20:59:00 [INFO] Starting WireGuard...
--------------------
Warning: `/config/wireguard/onelots.conf' is world accessible
[#] ip link add onelots type wireguard
[#] wg setconf onelots /dev/fd/63
[#] ip -4 address add 10.7.0.2/24 dev onelots
[#] ip link set mtu 1420 up dev onelots
[#] resolvconf -a onelots -m 0 -x
[#] wg set onelots fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev onelots table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] nft -f /dev/fd/63
--------------------
[cont-init.d] 20-vpn.sh: exited 0.
[cont-init.d] 30-network.sh: executing... 
[cont-init.d] 30-network.sh: exited 0.
[cont-init.d] 40-qbittorrent-setup.sh: executing... 
2024-05-12 20:59:00 [WARNING] ENABLE_SSL is set to , SSL is not enabled. This could cause issues with logging if other apps use the same Cookie name (SID).
2024-05-12 20:59:00 [WARNING] If you manage the SSL config yourself, you can ignore this.
2024-05-12 20:59:00 [WARNING] UMASK not defined (via -e UMASK), defaulting to '002'
[cont-init.d] 40-qbittorrent-setup.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
2024-05-12 20:59:00 [INFO] Logging to /config/qBittorrent/data/logs/qbittorrent.log.
[services.d] done.
2024-05-12 20:59:00 [INFO] Trying to ping 1.1.1.1 and 8.8.8.8 over the docker interface for 1 second...
2024-05-12 20:59:02 [INFO] Success: Could not connect. This means the firewall is most likely working properly.
2024-05-12 20:59:02 [INFO] qBittorrent started with PID 494```

Then my docker-compose.yml file : 

```yml
onelots@Server:~/torrent$ cat docker-compose.yml 
version: "3.3"

services:
  qbittorrent:
    image: trigus42/qbittorrentvpn:latest
    container_name: qbittorrent
    environment:
      - VPN_TYPE=wireguard
    volumes:
      - '../.config/:/config'
      - '../../../media/disk2/:/downloads/'
    ports:
     - 8080:8080
    restart: always
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
```

Thanks in advance 🙏

**Comment by Trigus42** [comment] 2024-05-13 16:17
The health-check times out. This causes the reboot. An easy fix would probably be to just set `HEALTH_CHECK_TIMEOUT=30` or something that.

Is it maybe the amount of bandwidth used that causes those errors? Does the same happen if you throttle the connection speed limit in QBt?  
To diagnose if this possibly is an issue with the container or the docker host, you can try setting `HEALTH_CHECK_HOST` to your docker host or your router/next hop device.

**Comment by Oneloutre** [comment] 2024-05-13 22:11
actually the host is perfectly fine, my infra doesn't have such problems, it happens only with qbittorrent.
I will setup HEALTH_CHECK_TIMEOUT=30 and i'll let you know if it changes sth. I appreciate the help 👍 thx

**Comment by Oneloutre** [comment] 2024-05-14 06:24
Great, I downloaded sth like 250Gb this night and everything worked, thanks. My only concern now is that I'm caped at 20Mbps but before I hade more than 40... Idk if maybe you know where it comes from ?

**Comment by leelouch** [comment] 2024-05-14 11:16
I may have the same problem, my download stops and restart over **without resuming what have been already downloaded** !
is this same what happen to you ? log below ... 
I will setup HEALTH_CHECK_TIMEOUT=30 and check again.

```
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2024-05-13 19:16:18 [INFO] Logging to /config/qBittorrent/data/logs/qbittorrent.log.
2024-05-13 19:16:18 [INFO] Trying to ping 1.1.1.1 and 8.8.8.8 over the docker interface for 1 second...
2024-05-13 19:16:20 [INFO] Success: Could not connect. This means the firewall is most likely working properly.
2024-05-13 19:16:20 [INFO] qBittorrent started with PID 502
2024-05-13 19:18:52 [NOTICE] Network seems to be down. Retrying..
2024-05-13 19:18:52 [ERROR] Network is down. Exiting..
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
```

**Comment by Oneloutre** [comment] 2024-05-14 11:21
Yeah do it, it was my problem too and adding this env var fixed it. It's really annoying that it re-download everything ahaha one time I was at 99Gb / 103 and it restarted... From the start 😂😂

**Comment by Oneloutre** [comment] 2024-05-14 11:23
Your docker compose should look like it :

```yml
version: "3.3"

services:
  qbittorrent:
    image: trigus42/qbittorrentvpn:latest
    container_name: qbittorrent
    environment:
      - VPN_TYPE=wireguard
      - HEALTH_CHECK_TIMEOUT=30
...
```

And it'll work

**Comment by leelouch** [comment] 2024-05-14 11:52
well I did it, unfortunately even 30 second is not enouph in some cases ! ( this depends a lot on the quality/load of the VPN server) 
just downloaded 30GB over 80GB and boom ! 
The think it is very weird that qbittorrent is not resuming the job after restarting ! Transmission client do it and it is very reliable ! 
Any idea on this ? 

```
2024-05-14 13:41:06 [NOTICE] Network seems to be down. Retrying..
2024-05-14 13:41:06 [NOTICE] Network connection restored
2024-05-14 13:41:27 [NOTICE] Network seems to be down. Retrying..
2024-05-14 13:41:47 [ERROR] Network is down. Exiting..
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
```

**Comment by Trigus42** [comment] 2024-05-14 12:12
Regarding the download speed: I don't know how this could have anything to do with this image. I would tend to blame the VPN provider, your connection or host machine. I am not sure about this though.

If you know that it is normal for your VPN connection to drop out for a certain time and you rather want to wait than reboot, just set `HEALTH_CHECK_TIMEOUT` to whatever you are expecting as normal/accepted downtime.

Regarding the issue of not resuming: This doesn't seem to be an unknown issue with QBt. If you have a temp download directory set, maybe try disabling that. Likely the same issue as [here](https://github.com/Trigus42/alpine-qbittorrentvpn/issues/61#issuecomment-2093261863).

**Comment by Oneloutre** [comment] 2024-05-14 13:55
I'm not aware of a temp dir (In any case, not setup by me, maybe by qbt by default... will look into it later.) About the internet speed, maybe the power of my VPS is limitating me, since the specs aren't wonderful (1 vCPU, 500Mb of ram and only 400Mbps for the bandwidth.)

But I have 1Gbps so internet speed is not the problem, I would tend to say that the bottleneck is my vps's speed.


@leelouch , what VPN provider are you using ? is it set up by you, or something such as protonvpn, ghost, nordvpn or other ?

**Comment by Oneloutre** [comment] 2024-05-14 14:17
I just looked into the qbt default settings, and I saw something interesting :

![Capture d’écran 2024-05-14 à 16 16 08](https://github.com/Trigus42/alpine-qbittorrentvpn/assets/54822802/4bdb0cfe-a3c5-4e47-b9ef-49c1130d34a1)


Under the default path for downloads, you have an option to tick if you want to keep the pending torrents... it's not activated by default, but activating it should help you

**Comment by leelouch** [comment] 2024-05-14 14:18
I dont have a temp directory, everything is by default regarding qbit configuration. 
my VPN provider is Nordvpn and I am using openvpn config file for my connection.
I am a transmission client user and wanted to move to something else due to a long stall delay after downloading big files with transmission.

**Comment by leelouch** [comment] 2024-05-14 14:18
Interresting, Oh ok , I will try this option to see if it change something.

**Comment by Oneloutre** [comment] 2024-05-14 14:25
great, let us know if it fixed your problem.
When everything will be fixed, i'll do a résumé in my 1st message to explain how to fix these bugs

**Comment by leelouch** [comment] 2024-05-14 15:32
No, even if the temp directory is set, when qbittorrent restart everything is removed, and download start over !
how qbittorrentvpn is killing qbittorrent ? is it a kill signal or a normal restart ? wonderring if this can be related ?

**Comment by Oneloutre** [comment] 2024-05-14 16:31
hmmmm 🤔 for me it seems that ticking this option solved the issue (my downloads are almost done but I launched like 200Gb and it restarted a couple of times, even with the healthcheck var)

maybe try to increase the healthcheck ?

**Comment by leelouch** [comment] 2024-05-14 18:52
I intentionally revert   healthcheck  to default value to accelerate the root cause, I will try to increase it and will check again.

**Comment by leelouch** [comment] 2024-05-15 16:08
Well, I confirm that I still have the issue ...

**Comment by leelouch** [comment] 2024-05-18 14:49
here are my observation: 
I tried a standalone installation of qbittorrent (outside docker)  qbittorrent-nox --version qBittorrent v4.4.1
I started a heavy download and I tried to killed in 2 different way ( sigterm or sigint ) 
in both case I hade this message : 
```
Catching signal: SIGTERM
Exiting cleanly
```
after restart, qbittorrent resumed it cleanly without any issue. 
even if if killed it with -9 signal with the message 
`Killed`
it resume the file without any issue. 
So what is happening in the docker ?

**Comment by Oneloutre** [comment] 2024-05-18 14:52
I don't really know, let's wait for Trigus to reply lol

**Comment by Trigus42** [comment] 2024-05-19 10:26
What is suspect is probably be happening here is that the resume files can not be written by QBt before the container exits. Killing QBt with SIGTERM allows it to write resume files before it exits. Killing it with SIGKILL leads to this issue for me; Same as restarting the container (don't know why SIGKILL didn't cause the problem in your tests @leelouch). 
So we just need to modify the behavior on exit using s6-overlay options.

As a quick fix, setting `Save resume data interval` in the advanced settings to `1` minute, which seems to be the minimum, should lead to less lost progress at last.

**Comment by leelouch** [comment] 2024-05-19 13:01
Ok, I did this, my results : 
loosed about 2% of download ( from 7% to 5% / from 9% to 8%) but resumed correctly
```
alpine-qbittorrent    | 2024-05-19 14:50:17 [INFO] qBittorrent started with PID 503
alpine-qbittorrent    | 2024-05-19 14:55:36 [NOTICE] Network seems to be down. Retrying..

or 
alpine-qbittorrent    | 2024-05-19 14:58:20 [INFO] qBittorrent started with PID 501
alpine-qbittorrent    | 2024-05-19 14:58:40 [NOTICE] Network seems to be down. Retrying..
alpine-qbittorrent    | 2024-05-19 14:58:40 [ERROR] Network is down. Exiting..
alpine-qbittorrent    | [cont-finish.d] executing container finish scripts...
alpine-qbittorrent    | [cont-finish.d] done.
alpine-qbittorrent    | [s6-finish] waiting for services.
alpine-qbittorrent    | [s6-finish] sending all processes the TERM signal.
alpine-qbittorrent    | [s6-finish] sending all processes the KILL signal and exiting
```
However, maybe it is better to delay the restart of the docker (about 15 seconds, or parametrable, or wait for pbt process to end) after killing qbt, no ?  (if this is possible)

**Comment by Trigus42** [comment] 2024-06-08 16:34
Please try the current `dev` image. It should hopefully fix the resume issue

**Comment by leelouch** [comment] 2024-06-11 15:30
Ok thanks, will check and will let you know

**Comment by leelouch** [comment] 2024-06-11 16:42
I am not able to start openvpn, any modification with the same configuration, I reverted to latest and it is working:

```
2024-06-11 17:36:42 [INFO] Using credentials from /config/openvpn/be148.nordvpn.com.tcp_credentials.conf
2024-06-11 17:36:42 [INFO] VPN_REMOTE defined as '82.102.19.137'
2024-06-11 17:36:42 [INFO] VPN_PORT defined as '443'
2024-06-11 17:36:42 [INFO] VPN_PROTOCOL defined as 'tcp'
2024-06-11 17:36:42 [INFO] VPN_DEVICE_TYPE defined as 'tun0'
2024-06-11 17:36:42 [INFO] Starting OpenVPN...
--------------------
Options error: --route-up script fails with '/helper/resume-after-connect': No such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.
--------------------
2024-06-11 17:36:42 [ERROR] Failed to start OpenVPN
```

**Comment by Trigus42** [comment] 2024-06-11 20:25
Thanks for testing! This problem should be fixed now. Please try the new image

**Comment by leelouch** [comment] 2024-06-11 20:42
no prob, started now, I will try to set data interval to 20 mn instead 1 and download a big file. 
will let you know.

**Comment by leelouch** [comment] 2024-06-11 21:02
Working ! Thanks

**Closed** 2024-07-15 14:25 UTC
